// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// matrixMultiplyEigen
Eigen::MatrixXd matrixMultiplyEigen(const Eigen::Map<Eigen::MatrixXd>& A, const Eigen::Map<Eigen::MatrixXd>& B);
RcppExport SEXP _POLARIS_matrixMultiplyEigen(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(matrixMultiplyEigen(A, B));
    return rcpp_result_gen;
END_RCPP
}
// matrixMultSparseDense
Eigen::MatrixXd matrixMultSparseDense(const Eigen::Map<Eigen::SparseMatrix<double> >& A, const Eigen::Map<Eigen::MatrixXd>& B);
RcppExport SEXP _POLARIS_matrixMultSparseDense(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::SparseMatrix<double> >& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(matrixMultSparseDense(A, B));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_POLARIS_matrixMultiplyEigen", (DL_FUNC) &_POLARIS_matrixMultiplyEigen, 2},
    {"_POLARIS_matrixMultSparseDense", (DL_FUNC) &_POLARIS_matrixMultSparseDense, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_POLARIS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
